name: Fluent UI for Flutter Client
on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows Client
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: git config --system core.longpaths true
      - name: Flutter Pub Get
        run: flutter pub get
        working-directory: ./example
      - name: Build for Windows
        run: flutter build windows --verbose
        working-directory: ./example

  # build_linux:
  #   name: Linux Client
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         submodules: recursive

  #     - run: sudo apt-get update -y
  #     - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #         cache: true
  #     - run: cd example
  #     - run: flutter pub get
  #     - run: flutter build linux --verbose

  build_macOS:
    name: macOS Client
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Build macOS
        run: flutter build macos --verbose
        working-directory: ./example
