name: Flutter Analysis
on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  workflow_dispatch:

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Run analysis
        run: flutter analyze

      - name: Verify package health
        run: flutter pub publish --dry-run

      - name: Run tests
        run: flutter test
