name: msix build
on:
  
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows Client
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: git config --system core.longpaths true
      - name: Flutter Pub Get
        run: flutter pub get
        working-directory: ./example
      - name: Build for Windows
        run: flutter build windows --verbose
        working-directory: ./example
      
      - name: Create MSIX Package
        run: |
          echo "create msix. version: ${{ steps.build-app.outputs.MSIX_PACKAGE_VERSION }}"
          flutter pub run msix:create --build-windows true --version ${{ steps.build-app.outputs.MSIX_PACKAGE_VERSION }} -v
          $msixPath = "build\windows\x64\runner\Release\flutter_app.msix"
          $newName = "FluentUIforFlutterClient.msix"
          Move-Item -Path $msixPath -Destination $newName -Force
          
      - name: Upload MSIX Package
        uses: actions/upload-artifact@v3
        with:
          name: FluentUIforFlutterClient
          path: ./example/build/windows/runner/Output/msix/Fluent_UI_for_Flutter_Client.msix
